inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - lib/**/*
    - bin/**/*
  Exclude:
    - example/**/*

Encoding:
 Enabled: false
RescueModifier:
 Enabled: false
HashSyntax:
 Enabled: false
SpaceInsideStringInterpolation:
  Enabled: false

# AbcSize:
#   Max: 24
# ClassLength:
#   Max: 256
# CyclomaticComplexity:
#   Max: 12
# LineLength:
#   Max: 120
# MethodLength:
#   Max: 32
# PerceivedComplexity:
#   Max: 12
