#!/usr/bin/env ruby

region 'us-east-1'
name 'convection-sqs-queue-example'

sqs_queue = template do
  description 'An example template for setting up a SQS queue with Convection'

  sqs_queue 'ExampleSQSQueue' do
    delay_seconds 0 # The time in seconds that delivery of messages is queued
    maximum_message_size 262144 # How many bytes a message can contain before it's rejected
    message_retention_period 345600 # The time in seconds a message stays in the queue
    queue_name 'ExampleSQSQueue' # The name of the queue
    receive_message_wait_time_seconds 0 # Set to non-zero to enable long polling
    visibility_timeout 30 # The time in seconds the queue will be unavailable once a message is delivered
  end
end

stack 'convection-sqs-queue-example', sqs_queue
